from test_suite import test_suite
from performance_measurment import print_times_per_functions
from performance_measurment import create_table_for_time_per_function

test_suite()
print_times_per_functions()
create_table_for_time_per_function()
